ruleset {

    description '''
        A Sample Groovy RuleSet containing all CodeNarc Rules
        You can use this as a template for your own custom RuleSet.
        Just delete the rules that you don't want to include.
        '''

    AbcComplexity
    AbstractClassName
    AbstractClassWithoutAbstractMethod
    AddEmptyString
    AssignmentInConditional
    BigDecimalInstantiation
    BooleanGetBoolean
    BooleanMethodReturnsNull
    BrokenOddnessCheck
    BusyWait
    CatchArrayIndexOutOfBoundsException
    CatchError
    CatchException
    CatchIllegalMonitorStateException
    CatchIndexOutOfBoundsException
    CatchNullPointerException
    CatchRuntimeException
    CatchThrowable
    ChainedTest
    ClassName
    ClassSize
    CloneableWithoutClone
    CloseWithoutCloseable
    CompareToWithoutComparable
    ConfusingClassNamedException
    ConfusingMethodName
    ConfusingTernary
    ConsecutiveLiteralAppends
    ConsecutiveStringConcatenation
    ConstantIfExpression
    ConstantTernaryExpression
    ConstantsOnlyInterface
    CoupledTestCase
    CyclomaticComplexity
    DeadCode
    DoubleCheckedLocking
    DoubleNegative
    DuplicateCaseStatement
    DuplicateImport
    DuplicateNumberLiteral
    DuplicateStringLiteral
    ElseBlockBraces
    EmptyCatchBlock
    EmptyElseBlock
    EmptyFinallyBlock
    EmptyForStatement
    EmptyIfStatement
    EmptyInstanceInitializer
    EmptyMethod
    EmptyMethodInAbstractClass
    EmptyStaticInitializer
    EmptySwitchStatement
    EmptySynchronizedStatement
    EmptyTryBlock
    EmptyWhileStatement
    EqualsAndHashCode
    ExceptionExtendsError
    ExplicitArrayListInstantiation
    ExplicitCallToAndMethod
    ExplicitCallToCompareToMethod
    ExplicitCallToDivMethod
    ExplicitCallToEqualsMethod
    ExplicitCallToGetAtMethod
    ExplicitCallToLeftShiftMethod
    ExplicitCallToMinusMethod
    ExplicitCallToModMethod
    ExplicitCallToMultiplyMethod
    ExplicitCallToOrMethod
    ExplicitCallToPlusMethod
    ExplicitCallToPowerMethod
    ExplicitCallToRightShiftMethod
    ExplicitCallToXorMethod
    ExplicitGarbageCollection
    ExplicitHashMapInstantiation
    ExplicitHashSetInstantiation
    ExplicitLinkedListInstantiation
    ExplicitStackInstantiation
    ExplicitTreeSetInstantiation
    FieldName
    FinalClassWithProtectedMember
    ForStatementBraces
    GStringAsMapKey
    GrailsPublicControllerMethod
    GrailsServletContextReference
    GrailsSessionReference
    GrailsStatelessService
    GroovyLangImmutable
    IfStatementBraces
    IllegalRegex
    ImplementationAsType
    ImportFromSamePackage
    InconsistentPropertyLocking
    InconsistentPropertySynchronization
    IntegerGetInteger
    InterfaceName
    InvertedIfElse
    JUnitAssertAlwaysFails
    JUnitAssertAlwaysSucceeds
    JUnitFailWithoutMessage
    JUnitPublicNonTestMethod
    JUnitSetUpCallsSuper
    JUnitStyleAssertions
    JUnitTearDownCallsSuper
    JUnitTestMethodWithoutAssert
    JUnitUnnecessarySetUp
    JUnitUnnecessaryTearDown
    LoggerForDifferentClass
    LoggerWithWrongModifiers
    LoggingSwallowsStacktrace
    MethodCount
    MethodName
    MethodSize
    MissingNewInThrowStatement
    MultipleLoggers
    NestedBlockDepth
    NestedSynchronization
    ObjectOverrideMisspelledMethodName
    PackageName
    ParameterName
    PrintStackTrace
    Println
    PropertyName
    RemoveAllOnSelf
    RequiredRegex
    ReturnFromFinallyBlock
    ReturnNullFromCatchBlock
    ReturnsNullInsteadOfEmptyArray
    ReturnsNullInsteadOfEmptyCollection
    SerialVersionUID
    SerializableClassMustDefineSerialVersionUID
    SimpleDateFormatMissingLocale
    StatelessClass
    StaticCalendarField
    StaticDateFormatField
    StaticMatcherField
    SynchronizedMethod
    SynchronizedOnBoxedPrimitive
    SynchronizedOnGetClass
    SynchronizedOnReentrantLock
    SynchronizedOnString
    SynchronizedOnThis
    SynchronizedReadObjectMethod
    SystemErrPrint
    SystemOutPrint
    SystemRunFinalizersOnExit
    ThreadGroup
    ThreadLocalNotStaticFinal
    ThreadYield
    ThrowError
    ThrowException
    ThrowExceptionFromFinallyBlock
    ThrowNullPointerException
    ThrowRuntimeException
    ThrowThrowable
    UnnecessaryBigDecimalInstantiation
    UnnecessaryBigIntegerInstantiation
    UnnecessaryBooleanExpression
    UnnecessaryBooleanInstantiation
    UnnecessaryCallForLastElement
    UnnecessaryCallToSubstring
    UnnecessaryCatchBlock
    UnnecessaryCollectCall
    UnnecessaryCollectionCall
    UnnecessaryConstructor
    UnnecessaryDefInMethodDeclaration
    UnnecessaryDoubleInstantiation
    UnnecessaryFail
    UnnecessaryFloatInstantiation
    UnnecessaryGString
    UnnecessaryGetter
    UnnecessaryGroovyImport
    UnnecessaryIfStatement
    UnnecessaryInstantiationToGetClass
    UnnecessaryIntegerInstantiation
    UnnecessaryLongInstantiation
    UnnecessaryModOne
    UnnecessaryNullCheck
    UnnecessaryNullCheckBeforeInstanceOf
    UnnecessaryObjectReferences
    UnnecessaryOverridingMethod
    UnnecessaryPublicModifier
    UnnecessaryReturnKeyword
    UnnecessarySelfAssignment
    UnnecessarySemicolon
    UnnecessaryStringInstantiation
    UnnecessaryTernaryExpression
    UnnecessaryTransientModifier
    UnusedArray
    UnusedImport
    UnusedObject
    UnusedPrivateField
    UnusedPrivateMethod
    UnusedPrivateMethodParameter
    UnusedVariable
    UseAssertEqualsInsteadOfAssertTrue
    UseAssertFalseInsteadOfNegation
    UseAssertNullInsteadOfAssertEquals
    UseAssertSameInsteadOfAssertTrue
    UseAssertTrueInsteadOfAssertEquals
    UseAssertTrueInsteadOfNegation
    UseOfNotifyMethod
    VariableName
    VolatileArrayField
    VolatileLongOrDoubleField
    WaitOutsideOfWhileLoop
    WhileStatementBraces
    
}